### ISSUE TITLE
Works also in Windows 11 with Miniconda3

### ISSUE THREAD

**Issue by zejacky** [hkchengrex/MMAudio#20]
Thank you very much for this very useful tool! Appreciate it.
I was able to successful install, and run on windows 11 with Miniconda3.

**Steps:**
conda create -n mmaudio python=3.9
conda activate mmaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --upgrade
git clone your repo
python gradio_demo.py

Works amazing.
Keep the good work!

**Comment by zejacky** [comment]
In this case, do you recommend Python 3.9 or is it "better" with 3.10 or 3.12 etc.? Thanks.

**Comment by hkchengrex** [comment]
Thanks for testing this on Windows. 
Regarding the Python version -- if it works, it works. There should not be any significant performance differences. I personally prefer newer versions, i.e., Python 3.11 at the moment because why not :) There are nice features like improved error messages: https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep657

**Comment by zejacky** [comment]
Thank you for your hint.
It tested also with python 3.12 and
pip install torch torchvision torchaudio --index-url  https://download.pytorch.org/whl/cu124 --upgrade
Works without problems.

**Comment by gee666** [comment]
on windows with python 3.12 and cuda 12.1 works perfectly

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --upgrade

**Comment by gee666** [comment]
it does display an error in the terminal though, but it works anyway:

```
[WARNING ]: Clip video is too short: 5.25 < 8.00
[WARNING ]: Truncating to 5.25 sec
[WARNING ]: Sync video is too short: 5.20 < 5.25
[WARNING ]: Truncating to 5.20 sec
[ERROR   ]: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
