### ISSUE TITLE
TypeError for gradio_demo

### ISSUE THREAD

**Issue by SoftologyPro** [hkchengrex/MMAudio#3]
This is under Windows when I run gradio_demo.py

```
Traceback (most recent call last):
  File "D:\Tests\MMAudio\MMAudio\gradio_demo.py", line 9, in <module>
    from mmaudio.eval_utils import (ModelConfig, all_model_cfg, generate, load_video, make_video,
  File "D:\Tests\MMAudio\MMAudio\mmaudio\eval_utils.py", line 15, in <module>
    from mmaudio.model.utils.features_utils import FeaturesUtils
  File "D:\Tests\MMAudio\MMAudio\mmaudio\model\utils\features_utils.py", line 12, in <module>
    from mmaudio.ext.mel_converter import MelConverter
  File "D:\Tests\MMAudio\MMAudio\mmaudio\ext\mel_converter.py", line 5, in <module>
    from librosa.filters import mel as librosa_mel_fn
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\librosa\filters.py", line 49, in <module>
    import scipy.signal
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\signal\__init__.py", line 320, in <module>
    from ._bsplines import *
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\signal\_bsplines.py", line 7, in <module>
    from ._signaltools import lfilter, sosfilt, lfiltic
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\signal\_signaltools.py", line 16, in <module>
    from ._ltisys import dlti
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\signal\_ltisys.py", line 29, in <module>
    from scipy.interpolate import make_interp_spline
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from ._interpolate import *
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\interpolate\_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\interpolate\_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "D:\Tests\MMAudio\MMAudio\venv\lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError
```

Any ideas?

To reproduce the issue try this batch file in an empty directory.
```
@echo off

echo *** %time% *** Deleting MMAudio directory if it exists
if exist MMAudio\. rd /S /Q MMAudio

echo *** %time% *** Cloning MMAudio repository
git clone https://github.com/hkchengrex/MMAudio
cd MMAudio

echo *** %time% *** Creating venv
python -m venv venv

echo *** %time% *** Activating venv
call venv\scripts\activate.bat

echo *** %time% *** Installing requirements
python -m pip install --upgrade pip
pip install -e .

echo *** %time% *** Installing GPU torch
pip uninstall -y torch
pip uninstall -y torch
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.5.1+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

echo *** %time% *** Patching typing_extensions
pip uninstall -y typing_extensions
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts typing_extensions==4.11.0

call venv\scripts\deactivate.bat
cd ..
echo *** %time% *** Finished MMAudio install
echo.
echo Check the stats for any errors.  Do not assume it worked.
pause
```

I do install CUDA torch 2.5.1.
I tried rolling back scipy to the previous few versions (as it seems to be a scipy related error?) but that makes no difference.

**Comment by SoftologyPro** [comment]
It was numpy.  Numpy 2.2.0 is installed with newest torch.  So need to uninstall numpy 2 and make sure 1.26.3 is installed.
Then it starts fine.

**Comment by hkchengrex** [comment]
Thanks. I think this is because `mmaudio` is installed before `torch`, so a new `numpy` gets installed. Ideally if we install `mmaudio` last, the maximum `numpy` version requirement in [pyproject.toml](https://github.com/hkchengrex/MMAudio/blob/main/pyproject.toml) would be enforced.

Hopefully, they can fix this soon, but meanwhile, I have updated the README to emphasize that torch should be installed first.
