### ISSUE TITLE
What is this torio package it fails. Failed to intialize FFmpeg extension

### ISSUE THREAD

**Issue by FurkanGozukara** [hkchengrex/MMAudio#6]
I have downloaded and tried ffmpeg 5.1 and 6.1 and both fails

here the logs

![image](https://github.com/user-attachments/assets/0c8599fc-fb63-428d-9ee4-57717b768d64)

```
Attempting to load FFmpeg versions: ['6', '5', '4', '']
Looking for extension: torio.lib._torio_ffmpeg6
Looking for library: libtorio_ffmpeg6
Checking for library at: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd
File exists?: True
Found library, attempting to load: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd
Error loading FFmpeg6: Could not find module 'R:\MMAudio_v1\MMAudio\venv\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Looking for extension: torio.lib._torio_ffmpeg5
Looking for library: libtorio_ffmpeg5
Checking for library at: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd
File exists?: True
Found library, attempting to load: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd
Error loading FFmpeg5: Could not find module 'R:\MMAudio_v1\MMAudio\venv\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Looking for extension: torio.lib._torio_ffmpeg4
Looking for library: libtorio_ffmpeg4
Checking for library at: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd
File exists?: True
Found library, attempting to load: R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd
Error loading FFmpeg4: Could not find module 'R:\MMAudio_v1\MMAudio\venv\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Looking for extension: torio.lib._torio_ffmpeg
Looking for library: libtorio_ffmpeg
Error loading FFmpeg: FFmpeg extension is not available.
Traceback (most recent call last):
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\gradio\blocks.py", line 2047, in process_api
    result = await self.call_function(
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\gradio\blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\gradio\utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "R:\MMAudio_v1\MMAudio\gradio_demo.py", line 60, in video_to_audio
    clip_frames, sync_frames, duration = load_video(video, duration)
  File "R:\MMAudio_v1\MMAudio\mmaudio\eval_utils.py", line 178, in load_video
    reader = StreamingMediaDecoder(video_path)
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\io\_streaming_media_decoder.py", line 526, in __init__
    self._be = ffmpeg_ext.StreamingMediaDecoder(os.path.normpath(src), format, option)
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\_extension\utils.py", line 29, in __getattr__
    self._import_once()
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\_extension\utils.py", line 43, in _import_once
    self.module = self.import_func()
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\_extension\utils.py", line 123, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers)
  File "R:\MMAudio_v1\MMAudio\venv\lib\site-packages\torio\_extension\utils.py", line 102, in _find_ffmpeg_extension
    raise ImportError(
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4', '']. Enable DEBUG logging to see more details about the error.
```

**Comment by FurkanGozukara** [comment]
pip freeze is here - i had 0 installation error
```

Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

R:\MMAudio_v1\MMAudio\venv\Scripts>activate

(venv) R:\MMAudio_v1\MMAudio\venv\Scripts>pip freeze
absl-py==2.1.0
aiofiles==23.2.1
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.7.0
asttokens==3.0.0
audioread==3.0.1
auraloss==0.4.0
av==14.0.1
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
cloudpickle==3.1.0
colorama==0.4.6
colorlog==6.9.0
comm==0.2.2
Cython==3.0.11
decorator==5.1.1
einops==0.8.0
exceptiongroup==1.2.2
executing==2.1.0
fastapi==0.115.6
ffmpeg-python==0.2.0
ffmpy==0.4.0
filelock==3.13.1
fsspec==2024.2.0
ftfy==6.3.1
future==1.0.0
gitdb==4.0.11
GitPython==3.1.43
gradio==5.9.0
gradio_client==1.5.2
grpcio==1.68.1
h11==0.14.0
hf_transfer==0.1.8
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.26.5
hydra-colorlog==1.2.0
hydra-core==1.3.2
idna==3.10
ipython==8.30.0
ipywidgets==8.1.5
jedi==0.19.2
Jinja2==3.1.3
joblib==1.4.2
jupyterlab_widgets==3.0.13
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mdurl==0.1.2
-e git+https://github.com/hkchengrex/MMAudio@8c375bd4781ce65809d6c0bba3b8cef285e299bb#egg=mmaudio
mpmath==1.3.0
msgpack==1.1.0
networkx==3.2.1
nitrous_ema==0.0.1
numba==0.60.0
numpy==1.26.3
omegaconf==2.3.0
open_clip_torch==2.29.0
opencv-python==4.10.0.84
orjson==3.10.12
packaging==24.2
pandas==2.2.3
parso==0.8.4
pillow==10.2.0
platformdirs==4.3.6
pooch==1.8.2
prompt_toolkit==3.0.48
protobuf==5.29.1
pure_eval==0.2.3
pycparser==2.22
pydantic==2.10.3
pydantic_core==2.27.1
pydub==0.25.1
Pygments==2.18.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.19
pytz==2024.2
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
rich==13.9.4
ruff==0.8.3
safehttpx==0.1.6
safetensors==0.4.5
scikit-learn==1.6.0
scipy==1.14.1
semantic-version==2.10.0
shellingham==1.5.4
six==1.17.0
smmap==5.0.1
sniffio==1.3.1
soundfile==0.12.1
soxr==0.5.0.post1
stack-data==0.6.3
starlette==0.41.3
sympy==1.13.1
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tensordict==0.6.1
threadpoolctl==3.5.0
timm==1.0.12
tomlkit==0.13.2
torch==2.5.1+cu124
torchaudio==2.5.1+cu124
torchdiffeq==0.2.5
torchvision==0.20.1+cu124
tqdm==4.67.1
traitlets==5.14.3
triton @ https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp310-cp310-win_amd64.whl
typer==0.15.1
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
uvicorn==0.33.0
wcwidth==0.2.13
websockets==14.1
Werkzeug==3.1.3
widgetsnbextension==4.0.13
xformers==0.0.28.post3

(venv) R:\MMAudio_v1\MMAudio\venv\Scripts>
```

**Comment by FurkanGozukara** [comment]
ok it turns out special dll files necessary for this to work

anyone knows how to get those with python venv instead of conda?

**Comment by thanhtvt** [comment]
@FurkanGozukara So how did you fix this? I've also encountered this issue. Did you manually install the `ffmpeg.dll` file or something?

**Comment by mkat2** [comment]
How did you fix it? im also runnning into this.

**Comment by hkchengrex** [comment]
@mkat2 Are you running training or inference? The current train should not require ffmpeg during inference. For training, you would need `ffmpeg<7`.

**Comment by mikkopparviainen** [comment]
@mkat2 I had the same problem while using torchaudio. The root cause was that torio didn't find libffi.so.7. The error message "ImportError: Failed to intialize FFmpeg..." doesn't reveal this issue.

In linux, the solution was to define environment variable:
LD_PRELOAD, that is,:
export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libffi.so.7"

**Comment by hadrien** [comment]
> made it work finally :D

:yuno: Can't you share how!??
