### ISSUE TITLE
No module named timm.layers

### ISSUE THREAD

**Issue by Neighkey** [hkchengrex/MMAudio#7]
sorry i'm a beginner to python and coding in general but i followed your guide but i'm getting this error

PS C:\Users\windows\Documents\GitHub\MMAudio> python gradio_demo.py
Traceback (most recent call last):
  File "C:\Users\windows\Documents\GitHub\MMAudio\gradio_demo.py", line 9, in <module>
    from mmaudio.eval_utils import (ModelConfig, all_model_cfg, generate, load_video, make_video,
  File "C:\Users\windows\Documents\GitHub\MMAudio\mmaudio\eval_utils.py", line 14, in <module>
    from mmaudio.model.utils.features_utils import FeaturesUtils
  File "C:\Users\windows\Documents\GitHub\MMAudio\mmaudio\model\utils\features_utils.py", line 13, in <module>
    from mmaudio.ext.synchformer import Synchformer
  File "C:\Users\windows\Documents\GitHub\MMAudio\mmaudio\ext\synchformer\__init__.py", line 1, in <module>
    from mmaudio.ext.synchformer.synchformer import Synchformer
  File "C:\Users\windows\Documents\GitHub\MMAudio\mmaudio\ext\synchformer\synchformer.py", line 7, in <module>
    from mmaudio.ext.synchformer.motionformer import MotionFormer
  File "C:\Users\windows\Documents\GitHub\MMAudio\mmaudio\ext\synchformer\motionformer.py", line 7, in <module>
    from timm.layers import trunc_normal_
ModuleNotFoundError: No module named 'timm.layers'

**Comment by hkchengrex** [comment]
Thanks for reporting. This is because your `timm` version is outdated. You can fix it with `pip install timm --upgrade`. I have updated `pyproject.toml` to reflect this version requirement.
