### ISSUE TITLE
ValueError: File object has no read() method, or readable() returned False.

### ISSUE THREAD

**Issue by ceria117** [hkchengrex/MMAudio#8]
Don't mind the prompt lol. But this occurs both using the demo.py and the gradio_demo.py with the same error. I am able to generate audio using prompts, but not from a video.

Edit: I have also tried running the sample clips and they do not work either.

ERROR USING DEMO.PY
(mmaudio) PS G:\AI-faster\MMAudio\MMAudio> python demo.py --duration=6 --video=G:\AI-faster\MMAudio\MMAudio\Bitcoin.mp4 --prompt "A man standing on the sidewalk yelling Bitcoin"
  INFO     | Loaded weights from weights\mmaudio_large_44k_v2.pth
  INFO     | Loaded hf-hub:apple/DFN5B-CLIP-ViT-H-14-384 model config.
  INFO     | Loading pretrained hf-hub:apple/DFN5B-CLIP-ViT-H-14-384 weights (C:\Users\jason\.cache\huggingface\hub\models--apple--DFN5B-CLIP-ViT-H-14-384\snapshots\f17177bb05c69c6336d0adbfc97e06d69f876904\open_clip_pytorch_model.bin).
  INFO     | Loading MotionFormer config from G:\AI-faster\MMAudio\MMAudio\mmaudio\ext\synchformer\divided_224_16x4.yaml
Loading weights from nvidia/bigvgan_v2_44khz_128band_512x
Removing weight norm...
  INFO     | Using video G:\AI-faster\MMAudio\MMAudio\Bitcoin.mp4
Traceback (most recent call last):
  File "G:\AI-faster\MMAudio\MMAudio\demo.py", line 135, in <module>
    main()
  File "E:\Python Install\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "G:\AI-faster\MMAudio\MMAudio\demo.py", line 90, in main
    video_info = load_video(video_path, duration)
  File "G:\AI-faster\MMAudio\MMAudio\mmaudio\eval_utils.py", line 177, in load_video
    output_frames, all_frames, orig_fps = read_frames(video_path,
  File "G:\AI-faster\MMAudio\MMAudio\mmaudio\data\av_utils.py", line 37, in read_frames
    with av.open(video_path) as container:
  File "av\container\core.pyx", line 401, in av.container.core.open
  File "av\container\core.pyx", line 246, in av.container.core.Container.__cinit__
  File "av\container\pyio.pyx", line 44, in av.container.pyio.PyIOFile.__cinit__
ValueError: File object has no read() method, or readable() returned False.

ERROR USING GRADIO_DEMO.PY
Traceback (most recent call last):
  File "E:\Python Install\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "E:\Python Install\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Python Install\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "E:\Python Install\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Python Install\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Python Install\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Python Install\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Python Install\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "E:\Python Install\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "G:\AI-faster\MMAudio\MMAudio\gradio_demo.py", line 82, in video_to_audio
    make_video(video_info, video_save_path, audio, sampling_rate=seq_cfg.sampling_rate)
  File "G:\AI-faster\MMAudio\MMAudio\mmaudio\eval_utils.py", line 217, in make_video
    reencode_with_audio(video_info, output_path, audio, sampling_rate)
  File "G:\AI-faster\MMAudio\MMAudio\mmaudio\data\av_utils.py", line 69, in reencode_with_audio
    container = av.open(output_path, 'w')
  File "av\container\core.pyx", line 411, in av.container.core.open
  File "av\container\core.pyx", line 246, in av.container.core.Container.__cinit__
  File "av\container\pyio.pyx", line 41, in av.container.pyio.PyIOFile.__cinit__
ValueError: File object has no write() method, or writable() returned False.

**Comment by hkchengrex** [comment]
Thanks for the report. What is your `av` version? `python -c "import av; print(av.__version__)"`

**Comment by hkchengrex** [comment]
Most likely fixed a newer version of `av` by https://github.com/PyAV-Org/PyAV/issues/1181 -- let me put a min version requirement for `av`. Let me know if updating `av` works for you! `pip install av --upgrade`

**Comment by ceria117** [comment]
av version was av-10.0.0
updating fixed it.
Thanks!
